### ISSUE TITLE
Please Release Version: 1.8.3

### ISSUE THREAD

**Issue by nwbarrett** [webjars/angularjs#148] opened 2022-06-29 19:03 UTC
The AngularJS team released an ultimate farewell 1.8.3 release.  Can we get a WebJar with the latest version?  Thanks!
See: https://github.com/angular/angular.js/tags

**Comment by jamesward** [comment] 2022-06-29 19:23
Duplicate of #147

**Closed as completed by jamesward** 2022-06-29 19:23 UTC
